llm:
  provider: fireworks
  fireworks:
    api_key_env: 
    model: accounts/fireworks/models/qwen2p5-vl-32b-instruct
    streaming: true
  openai:
    api_key_env: 
    model: gpt-4.1-mini

agent:
  type: react
  max_iterations: 15
  tools:
    - web_search
    - shell
    - file_read
    - file_write
    - file_search
    - list_directory

memory:
  backend: chroma
  k: 5
  persist_path: data/chroma

debug: true